import { questions, questionnaireTitles } from '../data/questions';
import { isQuestionComplete } from '../lib/questionnaire';
import type { Session } from '../types';
import { localized } from '../i18n';
import { useLanguage } from '../i18n/LanguageContext';

export function Drawer({session,current,onJump,onClose,onReview,onExport,onImport,onClear}:{session:Session;current:string;onJump:(id:string)=>void;onClose:()=>void;onReview:()=>void;onExport:()=>void;onImport:(file:File)=>void;onClear:()=>void}){
 const {language}=useLanguage(); const en=language==='en'; const groups=['current','childhood','sct'] as const;
 const sectionName=(question:typeof questions[number])=>localized(question.sectionLt,question.section,language).primary;
 return <><button className="scrim" aria-label={en?'Close menu':'Uždaryti meniu'} onClick={onClose}/><aside className="drawer" aria-label={en?'Contents':'Turinys'}><header><div><strong>{en?'Contents':'Turinys'}</strong></div><button aria-label={en?'Close':'Uždaryti'} onClick={onClose}>×</button></header><div className="drawer-scroll">{groups.map(qid=><section key={qid}><h2>{localized(questionnaireTitles[qid].lt,questionnaireTitles[qid].en,language).primary}</h2>{Array.from(new Set(questions.filter(q=>q.questionnaire===qid).map(q=>sectionName(q)))).map(section=>{const items=questions.filter(q=>q.questionnaire===qid&&sectionName(q)===section);const done=items.filter(q=>isQuestionComplete(q,session.answers[q.id],session.skipped)).length;return <div className="toc-section" key={section}><h3>{done===items.length?'✓ ':''}{section}<span>{done} / {items.length}</span></h3><div className="question-dots">{items.map(q=>{const complete=isQuestionComplete(q,session.answers[q.id],session.skipped);return <button key={q.id} aria-label={`${section}, ${en?'question':'klausimas'} ${q.number}, ${complete?(en?'answered':'atsakytas'):(en?'unanswered':'neatsakytas')}`} className={`${q.id===current?'current ':''}${complete?'done':'unanswered'}`} onClick={()=>onJump(q.id)}>{q.number}</button>})}</div></div>})}</section>)}</div><footer><button className="primary" onClick={onReview}>{en?'Review answers':'Peržiūrėti atsakymus'}</button><button onClick={onExport}>{en?'Export JSON':'Eksportuoti JSON'}</button><label className="file-button">{en?'Import JSON':'Importuoti JSON'}<input type="file" accept="application/json,.json" onChange={e=>e.target.files?.[0]&&onImport(e.target.files[0])}/></label><button className="danger" onClick={onClear}>{en?'Clear this session':'Išvalyti šią sesiją'}</button></footer></aside></>;
}
