import { frequencyChoices, settingLabels } from '../data/questions';
import type { Answer, LanguageMode, Question, Setting, SettingsAnswer } from '../types';
import { localized } from '../i18n';

export function QuestionControl({question,answer,onChange,invalid,language}:{question:Question;answer?:Answer;onChange:(a:Answer)=>void;invalid:boolean;language:LanguageMode}) {
 const en=language==='en';
 if(question.type==='frequency') return <div className={`frequency-grid ${invalid?'invalid':''}`} role="radiogroup" aria-label={en?'Response frequency':'Atsakymo dažnis'}>{frequencyChoices.map(c=>{const label=localized(c.lt,c.en,language);return <button key={c.value} type="button" role="radio" aria-checked={answer===c.value} className={answer===c.value?'selected':''} onClick={()=>onChange(c.value)}><strong>{c.value}</strong><span>{label.primary}</span></button>})}</div>;
 if(question.type==='yesno') return <div className={`yesno ${invalid?'invalid':''}`} role="radiogroup">{[[true,'Taip','Yes'],[false,'Ne','No']].map(([value,lt,en])=>{const label=localized(lt as string,en as string,language);return <button key={lt as string} type="button" className={answer===value?'selected':''} role="radio" aria-checked={answer===value} onClick={()=>onChange(value as boolean)}><strong>{label.primary}</strong>{label.secondary&&<span>{label.secondary}</span>}</button>})}</div>;
 if(question.type==='age') { const a=(answer&&typeof answer==='object'&&'age' in answer)?answer:{age:'',unknown:false}; return <div className={`age-control ${invalid?'invalid':''}`}><label>{en?'They were':'Asmeniui buvo'} <input aria-label={en?'Age in years':'Amžius metais'} type="number" inputMode="numeric" min="0" max="120" value={a.age} disabled={a.unknown} onChange={e=>onChange({age:e.target.value,unknown:false})} /> {en?'years old':'metų'}</label><label className="check"><input type="checkbox" checked={a.unknown} onChange={e=>onChange({age:'',unknown:e.target.checked})} /> {en?"I don’t know":'Nežinau'}</label></div>; }
 const empty:SettingsAnswer={selected:[],narratives:{}}; const a=(answer&&typeof answer==='object'&&'selected' in answer)?answer:empty;
 const toggle=(s:Setting)=>onChange({...a,selected:a.selected.includes(s)?a.selected.filter(x=>x!==s):[...a.selected,s]});
 const text=(s:Setting,lang:'lt'|'en',value:string)=>onChange({...a,narratives:{...a.narratives,[s]:{lt:a.narratives[s]?.lt||'',en:a.narratives[s]?.en||'',[lang]:value}}});
 return <div className={`settings ${invalid?'invalid':''}`}>{question.settings?.map(s=>{const label=localized(settingLabels[s].lt,settingLabels[s].en,language);return <div className="setting" key={s}><label className="setting-choice"><input type="checkbox" checked={a.selected.includes(s)} onChange={()=>toggle(s)} /><span><strong>{label.primary}</strong></span></label>{a.selected.includes(s)&&<div className="narratives"><label>{en?'Your response':'Jūsų atsakymas'}<textarea value={a.narratives[s]?.[language]||''} onChange={e=>text(s,language,e.target.value)} /></label>{!a.narratives[s]?.[language]&&<p className="warning">{en?'An example is requested, but you can continue.':'Prašoma pateikti pavyzdį, tačiau galite tęsti.'}</p>}</div>}</div>})}</div>;
}
